### ISSUE TITLE
Проблема при установке последней сборки 

### ISSUE THREAD

**Issue by Sarrinall** [Mitradis/Windows-10-DISM-Scripts#11]
![Снимок](https://github.com/user-attachments/assets/25b45d69-8937-4a0b-9e16-2bc1c3c70f1e)
При 2 перезагрузке выскакивает такое сообщение.

**Comment by Mitradis** [comment]
Образ не совпадает с контрольными суммами?

**Comment by Mitradis** [comment]
Исправлено https://github.com/Mitradis/DISM-Scripts-Tools/commit/78605fc56c482025e82c3949891dae259bcfcb65.
