### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by tagirov** [Mitradis/Windows-10-DISM-Scripts#2]
Хотелось бы. 
Спасибо за сборку! То, что нужно!!

**Comment by Mitradis** [comment]
Changelog в opensource? Ну разве что не посмотреть изменения в бекапах групповых политик, хотя это обновлено в справке, хотя ее изменения тоже не видно, но можно сравнить со старой. В последней версии добавлено только 
SmartScreen Защитника Windows: 
Explorer: 

Настроить компонент. (Отключить рекомендации) 
Расширенная защита: 
Служба включена. (Откл.)
