### ISSUE TITLE
powershell executionpolicy

### ISSUE THREAD

**Issue by AndShy** [Mitradis/Windows-10-DISM-Scripts#5]
в батнике неправильно указана `executionpolicy` для скрипта скачанного с интернета. нужно указать или `bypass `или делать `unblock-file `

**Comment by Mitradis** [comment]
Но скрипт не относится к скаченному из интернета, после распаковки .zip архива. Он без проблем выполняется.
Если я правильно понял вы предлагаете заменить  -executionpolicy remotesigned на  -executionpolicy bypass?

**Comment by AndShy** [comment]
Он как раз у меня не выполнялся именно из-за этого. Как там блокировка происходит - хз, но по факту файл заблокирован, хоть распакован из архива. Или в батнике разблокировку делать, или выполнять через `executionpolicy bypass`

**Comment by Mitradis** [comment]
https://github.com/Mitradis/Windows-10-DISM-Scripts/commit/4257d87389e480ea7352570f2cf8b16a504f94f9
