### ISSUE TITLE
Critical issue with explorer

### ISSUE THREAD

**Issue by AndShy** [Mitradis/Windows-10-DISM-Scripts#7]
После месяца работы винды (августовской столкнулся с зависанием проводника (повисает панель быстрого доступа, потом рабочий стол, потом программы). Причём, выяснить что именно повисает крайне сложно, т.к. даже не запускается диспетчер задач и винда сама не видит зависших программ. Думал, это связано с настройками конфиденциальности в проводнике, но, вот, во время написания этого текста проводник повис опять. Второй раз после правого клика по панели быстрого доступа. Так что с чем это связано - хз. Во время копаний в системе ещё обнаружил баг с "параметры" - достаточно кликнуть на "память", потом, например, на "фокусировка внимания" и снова на "память" и "параметры" вылетают. И вишенка на торте - после удаления classic shell родной "Пуск" не работает и сам classic shell просроченный - проект перешёл на github с названием open shell

**Comment by Mitradis** [comment]
"не запускается диспетчер задач" и "это связано с настройками конфиденциальности" не сочетаются никак. Ищите что ставили, чтото добавило свои библиотеки в оболочку возможно и приглючило.
"память" и "параметры" я в курсе, это ошибки самой ПУ. Индусы не умеют в проверки.
"classic shell просроченный" это самая нормальная и стабильная безбаговая версия. За 3 года ни разу не подвел.

**Comment by Mitradis** [comment]
Я точно не помню, но в предыдущих версиях в опции wintool Сбросить папки была лишняя опасная опция удаления ветки реестра. Возможно вы это использовали и получили небольшой баг с оболочкой. Делать ничего не нужно винда сама восстановит эти ключи. Ну по крайней мере у себя на винде я так удалил и тоже несколько дней падал эксплорер, а позже все прошло само. Ключ не могу точно назвать т.к. стерлись комиты после перезалива. Если скините свою wintool я скажу.

**Comment by Mitradis** [comment]
В старой версии WinTool, в опции сброса папок, могла быть строчка очистки вертки HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\CloudStore\Store\Cache\DefaultAccount
она была убрана, я не могу найти подтверждения того, что это было в августовской версии т.к. это было убрано довольно быстро в течении недели. Но если это так, то возможно причина в этом. Повторно очистите эту ветку, винда восстановит содержимое со временем, оболочка какое-то время может падать.

**Comment by AndShy** [comment]
Ок. Посмотрю поэксперементирую как будет время. Спасибо.

**Comment by AndShy** [comment]
перечитал снова, посмотрел что за wintool. Сборку делал сам, только контролируя скрипты на ошибки. установка - так же. вот только скрипты не хотели перезагружать винду. руками два раза ребутал. о существовании wintool даже не подозревал. месяц отработала без проблем. перед сбоями устанавливал только репак crysis remastered, т.к. сходу не получилось его распаковать, а сношаться не было желания. чаще всего проблема возникает при пользовании vivaldi, но после начала сбоев обновил сразу на следующую версию и проблема никуда не делась. 
ветку реестра удалил, попробую ещё попользоваться другим браузером.

**Comment by Mitradis** [comment]
общий сбой установки т.к. "вот только скрипты не хотели перезагружать винду" не должно быть. Нет логов установки, нет логов отработки скриптов по образу.

**Comment by AndShy** [comment]
дополнение. 
доставал передатчик для беспроводной клавы из usb - в usb осталась металлическая часть разъёма. вполне возможно, что это и было причиной глюков, которые винда обрабатывала весьма в странный способ. разъём собрал, посмотрим на дальнейшее поведение винды.

**Comment by AndShy** [comment]
Я исчерпал все варианты. Всё работает, всё, вроде, как и должно быть, а винда повисает. Буду накатывать другую сборку. 
![1699551568186-01](https://github.com/Mitradis/Windows-10-DISM-Scripts/assets/15649615/54f81d88-1672-474b-b3bb-4817a615eb57)
